development:
  adapter: postgresql
  encoding: unicode
  database: expense_report_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: expense_report_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: expense_report_production
  pool: 5
